
DROP TABLE IF EXISTS emp;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS dept;

CREATE TABLE dept (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  dept_id INTEGER,
  CONSTRAINT fk_dept
    FOREIGN KEY (dept_id)
    REFERENCES dept(id)
    ON DELETE SET NULL
);

CREATE TABLE emp (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER,
  manager_id INTEGER,
  CONSTRAINT fk_role
    FOREIGN KEY (role_id)
    REFERENCES role(id)
    ON DELETE SET NULL,
  CONSTRAINT fk_manager
    FOREIGN KEY (manager_id)
    REFERENCES emp(id)
    ON DELETE SET NULL
);

